---
title: "Manipulate"
author: "C Paterson"
date: "6/28/2021"
output: 
  html_document: 
    toc: true
    toc_depth: 3
    toc_float: true
    code_folding: "show"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 2.1 

### 2.1.1 Create manipulate.rmd

### Read online table

### Download table ('*.csv')

### Get URL to CSV
### Download CSV

```{r}
# set variables
csv_url  <- "https://oceanview.pfeg.noaa.gov/erddap/tabledap/cciea_AC.csv"
dir_data <- "data"

# derived variables
csv <- file.path(dir_data, basename(csv_url))

# create directory
dir.create(dir_data)

# download file
download.file(csv_url, csv)
```
### 2.1.4 Read table 'read.csv()'

```{r}
# attempt to read csv
d <- read.csv(csv)

# show the data frame
#d

# read csv by skipping first two lines, so no header. Do this since data has two lines of header and we don't want the second line of header to be counted as a row in the table.
#d <- read.csv(csv, skip=2, header=FALSE)

# show the data frame
#d

# update data frame to original column names
#names(d) <- names(read.csv(csv))
#d
```

### 2.1.5 Show table `DT::datatable()`
```{r}
DT::datatable(d)
```

## 2.2 Wrangle Data

### 2.2.2 Manipulate with 'dplyr'

```{r}
library(DT)
library(dplyr)

d <- d %>% 
  # tibble
  tibble() %>% 
  # mutate time
  mutate(
    time = as.Date(substr(time, 1, 10))) %>% 
  # select columns
  select(
    time, 
    starts_with("total_fisheries_revenue")) %>% 
  # filter rows
  filter(
    time >= as.Date("1981-01-01"))

datatable(d)
```

### 2.2.3 Tidy with 'tidyr'

```{r}
library(tidyr)

d <- d %>% 
  pivot_longer(-time)

datatable(d)
```

### 2.2.4 Summarize with 'diplyr'

```{r}
library(stringr)

d <- d %>% 
  mutate(
    region = str_replace(name, "total_fisheries_revenue_", "")) %>% 
  select(time, region, value)
datatable(d)

d_sum <- d %>% 
  group_by(region) %>% 
  summarize(
    avg_revenue = mean(value))
datatable(d_sum) %>% 
  formatCurrency("avg_revenue")
```

### 2.2.5 Apply functions with 'purr' on a 'nest''ed 'tibble'

```{r}
library(purrr)

n <- d %>% 
  group_by(region) %>% 
  nest(
    data = c(time, value))
n

n <- n %>% 
  mutate(
    lm    = map(data, function(d){
      lm(value ~ time, d) } ),
    trend = map_dbl(lm, function(m){
      coef(summary(m))["time","Estimate"] }))
n
n %>% 
  select(region, trend) %>% 
  datatable()
```

